### ISSUE TITLE
Exception when trying to use 64 digit key

### ISSUE THREAD

**Issue by lasergoat** [AdSegura/node-laravel-encryptor#1]
FIrst off, thank you for making this repo!

```
node -v
v10.16.0
```

**Using this code:**

```
    const { Encryptor } = require("node-laravel-encryptor");
    const key = Encryptor.generateRandomKey(64, "base64");

    let encryptor = new Encryptor({
      key: key,
      key_length: 64
    });

    const result = encryptor.encryptSync("TEXTTOENCRYPT");
    console.log(result);
```

Exception is thrown:

```
     EncryptorError: Invalid key length
      at Function.throwError (node_modules/node-laravel-encryptor/dist/base_encryptor.js:256:15)
      at Encryptor.createCipher (node_modules/node-laravel-encryptor/dist/base_encryptor.js:144:28)
      at Encryptor.encryptItSync (node_modules/node-laravel-encryptor/dist/base_encryptor.js:35:29)
      at Encryptor.encryptSync (node_modules/node-laravel-encryptor/dist/Encryptor.js:21:50)
```

Yet, if I make a key of 32 and don't pass a key_length into the Encryptor constructor, it works. It's like the cipher algorithm isn't being set properly when the key is 64 digits.

**Comment by lasergoat** [comment]
When I use a 32 bit Key, it encrypts, but I am unable to make the encryptor instance in laravel:

```
    const originalPassword = "98b29b3b";

    const { Encryptor } = require("node-laravel-encryptor");
    const key = Encryptor.generateRandomKey(32);

    // copy this key to paste into laravel
    console.log("key:", key.toString("base64"));

    let encryptor = new Encryptor({
      key
    });

    const result = encryptor.encryptSync(originalPassword);
    console.log("base_encryptor.js:", result);
```

Now, take that key, and the encryption and use in `artisan tinker` for decryption:

```
// run php artisan tinker

$newEncrypter = new \Illuminate\Encryption\Encrypter( base64_decode('SrA+WaJ9CZilLJ51WWdQl/nor/6xMJ779yhi4JK43bk='), 'AES-128-CBC' );

// ERROR: RuntimeException with message 'The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.'

```

<img width="619" alt="Screen Shot 2020-01-09 at 9 33 48 AM" src="https://user-images.githubusercontent.com/15964/72080902-26409680-32c3-11ea-9eb7-6c3ffc397f73.png">

**Comment by AdSegura** [comment]
Hi.

Sorry for the delay answering , right now I'm not able to dig into it but I'll look this issue more carefully when I finish to settle down.

**Comment by AdSegura** [comment]
> FIrst off, thank you for making this repo!
> 
> ```
> node -v
> v10.16.0
> ```
> 
> **Using this code:**
> 
> ```
>     const { Encryptor } = require("node-laravel-encryptor");
>     const key = Encryptor.generateRandomKey(64, "base64");
> 
>     let encryptor = new Encryptor({
>       key: key,
>       key_length: 64
>     });
> 
>     const result = encryptor.encryptSync("TEXTTOENCRYPT");
>     console.log(result);
> ```
> 
> Exception is thrown:
> 
> ```
>      EncryptorError: Invalid key length
>       at Function.throwError (node_modules/node-laravel-encryptor/dist/base_encryptor.js:256:15)
>       at Encryptor.createCipher (node_modules/node-laravel-encryptor/dist/base_encryptor.js:144:28)
>       at Encryptor.encryptItSync (node_modules/node-laravel-encryptor/dist/base_encryptor.js:35:29)
>       at Encryptor.encryptSync (node_modules/node-laravel-encryptor/dist/Encryptor.js:21:50)
> ```
> 
> Yet, if I make a key of 32 and don't pass a key_length into the Encryptor constructor, it works. It's like the cipher algorithm isn't being set properly when the key is 64 digits.

I just published an update.

Now `options.key_length` should be 128 or 256 to reflect what Laravel is ussing, aes-128-cbc or aes-256-cbc

`generateRandomKey` too:

```js
const key = Encryptor.generateRandomKey();
const key = Encryptor.generateRandomKey(128);
```

Thanks for the advise and let me know if you have any problem.
